import dotenv from "dotenv"

dotenv.config()

export default {
    MONGO_DB_CONNECTION_STRING: process.env.MONGO_DB_CONNECTION_STRING,
    MONGO_DB_NAME: process.env.MONGO_DB_NAME,
    MONGO_CHARACTERS_COLLECTION_NAME:
        process.env.MONGO_CHARACTERS_COLLECTION_NAME,
    MONGO_CONVERSATIONS_COLLECTION_NAME:
        process.env.MONGO_CONVERSATIONS_COLLECTION_NAME,
    AZURE_STORAGE_ACCOUNT_NAME: process.env.AZURE_STORAGE_ACCOUNT_NAME,
    AZURE_STORAGE_AUDIO_CONTAINER_NAME:
        process.env.AZURE_STORAGE_AUDIO_CONTAINER_NAME,
    AZURE_STORAGE_AVATAR_CONTAINER_NAME:
        process.env.AZURE_STORAGE_AVATAR_CONTAINER_NAME,
    AZURE_STORAGE_MESSAGE_AUDIO_CONTAINER_NAME:
        process.env.AZURE_STORAGE_MESSAGE_AUDIO_CONTAINER_NAME,
    OPEN_AI_API_KEY: process.env.OPEN_AI_API_KEY,
    AZURE_SPEECH_KEY: process.env.SPEECH_KEY,
    AZURE_SPEECH_REGION: process.env.SPEECH_REGION,
}
